### ISSUE TITLE
[Feature]: ページ (すべて)

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#114]
# Tasks (Features)

TEAM PIPLUP

@duke-imo @HIMA-HIMAZIN @kou-nagamine @nafell @Shvain @YoshieYuushi @wiyco

## Overview of Tasks (Features)

タスクの概要

すべてのページを司るissue

## Todo

想定される作業

- [x] サインアップ - 初期 #121 
- [x] サインアップ - 確認コード #122 
- [x] サインアップ - エラー (確認コード) #90 
- [x] サインアップ - データ利用 (プライバシー) #89 
- [x] メイン - ホーム #111 
- [x] メイン - ランキング #123 
- [x] メイン - カレンダー #124
- [x] メイン - アカウント (サインイン/サインアップ) #129 
- [x] おすすめ - Quantity #35 
- [x] おすすめ - Price #35 
- [x] おすすめ - Taste #35 
- [x] おすすめ - ローディング (検索しています...) #113 
- [x] おすすめ - 結果 #36 
- [x] 詳細 - 料理 #125
- [x] 詳細 - ルート案内 (お店) #126

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
