### ISSUE TITLE
[Feature]: ディレクトリ及びその`layout`s

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#136]
# Tasks (Features)

TEAM PIPLUP

@duke-imo @HIMA-HIMAZIN @kou-nagamine @nafell @Shvain @YoshieYuushi @wiyco

## Overview of Tasks (Features)

タスクの概要

全ディレクトリ(ページ)の`layout`sとその構造

![Page-flow_for-export_v2 0](https://github.com/wiyco/imap/assets/72733890/6459cd37-24f2-4a60-90b0-4c442b48317c)

## Todo

想定される作業

- [x] `layout.tsx`の追加
- [x] meta tag (title)の追加

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
