### ISSUE TITLE
[Feature]: API-Route (すべて)

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#164]
# Tasks (Features)

TEAM PIPLUP

@duke-imo @HIMA-HIMAZIN @kou-nagamine @nafell @Shvain @wiyco

## Overview of Tasks (Features)

タスクの概要

すべての `api route` を司るissue

## Todo

想定される作業

- [x] RLS - `migration.sql` or supabase (define in supabase-sql-editor is better)
- [x] Trigger and func of user creation/update/deletion (maybe define on supabase) ON SUPABASE
- [x] Middleware - アクセス制限 #132 
- [x] サインアップ - 初期 #132 
- [x] サインアップ - 確認コード #132 
- [x] サインアップ - エラー (確認コード) #132 
- [x] データ利用 (プライバシー) - 同意ステータス #169
- [x] おすすめ
  - [x] おすすめ - テストケース
  - [x] おすすめ - route
  - [x] おすすめ - 検索 #37 
  - [x] おすすめ - ローディング (検索しています...) [間に挟む/api-routeではない]
  - [x] おすすめ - 結果 #37 
- [x] 料理 #171
  - [x] 料理 - テストケース
  - [x] 料理 - route
  - [x] 料理 - ここへ行く route
  - [x] 料理 - pageでリクエスト・表示処理
- [x] ホーム #170
  - [x] ホーム - テストケース
  - [x] 今月の開拓数 - route
  - [x] 今月の開拓数 - pageでリクエスト・表示処理
- [x] ユーザー
  - [x] 何を書く必要がある？もしかしてこれ要らない？
- [x] ルート案内 #172
  - [x] ルート案内 - テストケース
  - [x] ルート案内 - route
  - [x] ルート案内 - pageでリクエスト・表示処理
- [x] Routeでユーザー認証

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
