### ISSUE TITLE
[Feature]: インフォメーションダイアログ

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#39]
# Tasks (Features)

TEAM PIPLUP

@HIMA-HIMAZIN

## Overview of Tasks (Features)

タスクの概要

`インフォメーションダイアログ`のコンポーネント

- `確認コードが届きません`
- `私たちが考えるプライバシー`

![image](https://github.com/wiyco/imap/assets/72733890/928f4d19-3a17-4654-8dbd-3a9345378e20)

## Todo

想定される作業

- [x] コンポーネント名は `DialogInfo` にする。
- [x] コンポーネントは `src/components/dialogs/` に置く。
- [x] [`Material UI - Dialog`](https://mui.com/material-ui/react-dialog/#scrolling-long-content)を使う。
- [x] 閉じるアイコンは `SF Symbols` の `xmark` を使う。
- [x] `icon` は `public/icons/` に置く。

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
