### ISSUE TITLE
[Feature]: 店舗・料理情報の入力

### ISSUE THREAD

**Issue by nafell** [wiyco/imap#44]
# Tasks (Features)

TEAM PIPLUP

## Overview of Tasks (Features)

タスクの概要

店舗情報をDBに手入力するのは現実的ではないため、入力用のツールが必要
ユーザー側に公開するかしないか（ユーザーが情報を編集できるようにする）は要検討

## Todo

想定される作業

- [ ] エンドユーザー画面 or 管理画面
  - [ ] 店舗一覧 (画面)
  - [ ] 店舗//料理一覧  (画面)
- [ ] 編集UI
  - [ ] 店舗情報編集  (画面)
  - [ ] 料理情報編集  (画面)
  - [ ] プレビュー画面（確認画面）
- [ ] 編集権限の制限

または

- [x] 未正規化状態のCSVを読み込むスクリプトを作成する

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。

**Comment by wiyco** [comment]
[nafell - db/seed](https://github.com/nafell/imap/tree/db/seed)にて対応完了
