### ISSUE TITLE
[Feature]: 戻るボタン

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#45]
# Tasks (Features)

TEAM PIPLUP

@HIMA-HIMAZIN

## Overview of Tasks (Features)

タスクの概要

`戻る` のボタンコンポーネント

- `店舗詳細`
- `おすすめ結果`
- その他

![image](https://github.com/wiyco/imap/assets/72733890/048ceca8-751d-4569-8057-a5b40cde88ca)

## Todo

想定される作業

- [x] コンポーネント名は `BackButton` 
- [x] コンポーネントは `@/component/buttons/` に置く
- [x] アイコンは [iconoir](https://iconoir.com/) の `nav-arrow-left` を使う
- [x] 処理は [Next.jsの`useRouter`](https://nextjs.org/docs/app/api-reference/functions/use-router) を参考にすること。

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
