### ISSUE TITLE
[Feature]: カード

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#75]
# Tasks (Features)

TEAM PIPLUP

@YoshieYuushi

## Overview of Tasks (Features)

タスクの概要

カードコンポーネント

![image](https://github.com/wiyco/imap/assets/72733890/8254552c-75c9-417e-bd4d-2391df9e4eec)

## Todo

想定される作業

- [x] コンポーネント名(フォルダ)は `Card` 
- [ ] `backdrop-blur` をつける

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
