### ISSUE TITLE
[Feature]: 拡大パネル (カード)

### ISSUE THREAD

**Issue by wiyco** [wiyco/imap#77]
# Tasks (Features)

TEAM PIPLUP 🐧

@wiyco

## Overview of Tasks (Features)

タスクの概要

コンポーネント

![image](https://github.com/wiyco/imap/assets/72733890/aac509c8-be3d-4c46-9080-e752b045da31)
![image](https://github.com/wiyco/imap/assets/72733890/c6f21c7f-fb06-4f0e-a858-fd11b12bd457)

## Todo

想定される作業

- [x] コンポーネント名は `ExpandablePanel`
- [x] 汎用性を高めるため`ReactNode`(children)引数を設定する
- [ ] ~~開く、閉じるで高さが変わる→アニメーションをつける~~

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
